import { PrismaClient, Level, Currency, Source } from '../node_modules/@prisma/client'
import { PrismaNeon } from '../node_modules/@prisma/adapter-neon'
import * as dotenv from 'dotenv'
dotenv.config()

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })


// ─────────────────────────────────────────────────────────────────────────────
// Company definitions
// Demonstrates normalization: "Google India", "GOOGLE", "google" → slug "google"
// ─────────────────────────────────────────────────────────────────────────────

const companies = [
  {
    name: 'Google',
    slug: 'google',
    normalized_name: 'google',
    industry: 'Technology',
    headquarters: 'Mountain View, CA',
    founded_year: 1998,
    headcount_range: '100000+',
  },
  {
    name: 'Amazon',
    slug: 'amazon',
    normalized_name: 'amazon',
    industry: 'E-commerce / Cloud',
    headquarters: 'Seattle, WA',
    founded_year: 1994,
    headcount_range: '1000000+',
  },
  {
    name: 'Meta',
    slug: 'meta',
    normalized_name: 'meta',
    industry: 'Social Media / Technology',
    headquarters: 'Menlo Park, CA',
    founded_year: 2004,
    headcount_range: '50000-100000',
  },
  {
    name: 'Microsoft',
    slug: 'microsoft',
    normalized_name: 'microsoft',
    industry: 'Technology / Cloud',
    headquarters: 'Redmond, WA',
    founded_year: 1975,
    headcount_range: '100000+',
  },
  {
    name: 'Flipkart',
    slug: 'flipkart',
    normalized_name: 'flipkart',
    industry: 'E-commerce',
    headquarters: 'Bengaluru, India',
    founded_year: 2007,
    headcount_range: '10000-50000',
  },
  {
    name: 'Meesho',
    slug: 'meesho',
    normalized_name: 'meesho',
    industry: 'E-commerce / Social Commerce',
    headquarters: 'Bengaluru, India',
    founded_year: 2015,
    headcount_range: '5000-10000',
  },
  {
    name: 'NVIDIA',
    slug: 'nvidia',
    normalized_name: 'nvidia',
    industry: 'Semiconductors / AI',
    headquarters: 'Santa Clara, CA',
    founded_year: 1993,
    headcount_range: '20000-50000',
  },
  {
    name: 'Tata Consultancy Services',
    slug: 'tcs',
    normalized_name: 'tcs',
    industry: 'IT Services',
    headquarters: 'Mumbai, India',
    founded_year: 1968,
    headcount_range: '500000+',
  },
  {
    name: 'Infosys',
    slug: 'infosys',
    normalized_name: 'infosys',
    industry: 'IT Services',
    headquarters: 'Bengaluru, India',
    founded_year: 1981,
    headcount_range: '300000+',
  },
  {
    name: 'Wipro',
    slug: 'wipro',
    normalized_name: 'wipro',
    industry: 'IT Services',
    headquarters: 'Bengaluru, India',
    founded_year: 1945,
    headcount_range: '200000+',
  },
  {
    name: 'Razorpay',
    slug: 'razorpay',
    normalized_name: 'razorpay',
    industry: 'Fintech',
    headquarters: 'Bengaluru, India',
    founded_year: 2014,
    headcount_range: '3000-5000',
  },
  {
    name: 'Zepto',
    slug: 'zepto',
    normalized_name: 'zepto',
    industry: 'Quick Commerce',
    headquarters: 'Mumbai, India',
    founded_year: 2021,
    headcount_range: '5000-10000',
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Helper: compute total_compensation server-side ALWAYS
// ─────────────────────────────────────────────────────────────────────────────
function tc(base: number, bonus: number = 0, stock: number = 0): bigint {
  return BigInt(base + bonus + stock)
}

async function main() {
  console.log('🌱 Seeding TalentDash database...')

  // Upsert companies
  const companyMap: Record<string, string> = {}
  for (const c of companies) {
    const company = await prisma.company.upsert({
      where: { slug: c.slug },
      update: {},
      create: c,
    })
    companyMap[c.slug] = company.id
  }

  console.log(`✅ Created ${companies.length} companies`)

  // Delete existing salary records (clean seed)
  await prisma.salary.deleteMany()

  const salaryData = [
    // ── GOOGLE ────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['google'],
      role: 'Software Engineer',
      level: Level.L3,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 1,
      base_salary: BigInt(2000000),
      bonus: BigInt(300000),
      stock: BigInt(500000),
      total_compensation: tc(2000000, 300000, 500000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.92,
    },
    {
      company_id: companyMap['google'],
      role: 'Software Engineer',
      level: Level.L4,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 4,
      base_salary: BigInt(3500000),
      bonus: BigInt(600000),
      stock: BigInt(1500000),
      total_compensation: tc(3500000, 600000, 1500000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.95,
    },
    {
      company_id: companyMap['google'],
      role: 'Software Engineer',
      level: Level.L5,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 7,
      base_salary: BigInt(5000000),
      bonus: BigInt(1200000),
      stock: BigInt(4000000),
      total_compensation: tc(5000000, 1200000, 4000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.93,
    },
    {
      company_id: companyMap['google'],
      role: 'Software Engineer',
      level: Level.L6,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 12,
      base_salary: BigInt(7500000),
      bonus: BigInt(2000000),
      stock: BigInt(10000000),
      total_compensation: tc(7500000, 2000000, 10000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },
    {
      company_id: companyMap['google'],
      role: 'Product Manager',
      level: Level.L5,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 8,
      base_salary: BigInt(4800000),
      bonus: BigInt(1100000),
      stock: BigInt(3500000),
      total_compensation: tc(4800000, 1100000, 3500000),
      source: Source.SCRAPED,
      confidence_score: 0.72,
    },
    {
      company_id: companyMap['google'],
      role: 'Staff Engineer',
      level: Level.STAFF,
      location: 'San Francisco',
      currency: Currency.USD,
      experience_years: 14,
      base_salary: BigInt(300000), // $300,000
      bonus: BigInt(50000),
      stock: BigInt(250000),
      total_compensation: tc(300000, 50000, 250000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.97,
    },
    // Edge case: very high equity
    {
      company_id: companyMap['google'],
      role: 'Principal Engineer',
      level: Level.PRINCIPAL,
      location: 'San Francisco',
      currency: Currency.USD,
      experience_years: 20,
      base_salary: BigInt(400000), // $400,000
      bonus: BigInt(80000),
      stock: BigInt(4000000),
      total_compensation: tc(400000, 80000, 4000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.88,
    },

    // ── AMAZON ────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['amazon'],
      role: 'Software Development Engineer',
      level: Level.SDE_I,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(2200000),
      bonus: BigInt(400000),
      stock: BigInt(800000),
      total_compensation: tc(2200000, 400000, 800000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.91,
    },
    {
      company_id: companyMap['amazon'],
      role: 'Software Development Engineer',
      level: Level.SDE_II,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 5,
      base_salary: BigInt(4200000),
      bonus: BigInt(800000),
      stock: BigInt(2000000),
      total_compensation: tc(4200000, 800000, 2000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.94,
    },
    {
      company_id: companyMap['amazon'],
      role: 'Software Development Engineer',
      level: Level.SDE_III,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 9,
      base_salary: BigInt(6000000),
      bonus: BigInt(1500000),
      stock: BigInt(5000000),
      total_compensation: tc(6000000, 1500000, 5000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },
    // Edge case: zero bonus
    {
      company_id: companyMap['amazon'],
      role: 'Data Analyst',
      level: Level.L4,
      location: 'Hyderabad',
      currency: Currency.INR,
      experience_years: 3,
      base_salary: BigInt(1800000),
      bonus: BigInt(0),
      stock: BigInt(400000),
      total_compensation: tc(1800000, 0, 400000),
      source: Source.SCRAPED,
      confidence_score: 0.65,
    },
    {
      company_id: companyMap['amazon'],
      role: 'Software Development Engineer',
      level: Level.SDE_II,
      location: 'Mumbai',
      currency: Currency.INR,
      experience_years: 6,
      base_salary: BigInt(3800000),
      bonus: BigInt(700000),
      stock: BigInt(1500000),
      total_compensation: tc(3800000, 700000, 1500000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.88,
    },
    {
      company_id: companyMap['amazon'],
      role: 'Principal Engineer',
      level: Level.PRINCIPAL,
      location: 'Seattle',
      currency: Currency.USD,
      experience_years: 18,
      base_salary: BigInt(380000),
      bonus: BigInt(60000),
      stock: BigInt(300000),
      total_compensation: tc(380000, 60000, 300000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.85,
    },

    // ── META ──────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['meta'],
      role: 'Software Engineer',
      level: Level.IC4,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 5,
      base_salary: BigInt(4500000),
      bonus: BigInt(900000),
      stock: BigInt(3000000),
      total_compensation: tc(4500000, 900000, 3000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.93,
    },
    {
      company_id: companyMap['meta'],
      role: 'Software Engineer',
      level: Level.IC5,
      location: 'London',
      currency: Currency.GBP,
      experience_years: 10,
      base_salary: BigInt(220000),
      bonus: BigInt(40000),
      stock: BigInt(150000),
      total_compensation: tc(220000, 40000, 150000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.89,
    },
    {
      company_id: companyMap['meta'],
      role: 'Product Manager',
      level: Level.IC4,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 7,
      base_salary: BigInt(4000000),
      bonus: BigInt(800000),
      stock: BigInt(2500000),
      total_compensation: tc(4000000, 800000, 2500000),
      source: Source.SCRAPED,
      confidence_score: 0.7,
    },

    // ── MICROSOFT ─────────────────────────────────────────────────────────────
    {
      company_id: companyMap['microsoft'],
      role: 'Software Engineer',
      level: Level.L4,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 4,
      base_salary: BigInt(3200000),
      bonus: BigInt(550000),
      stock: BigInt(1200000),
      total_compensation: tc(3200000, 550000, 1200000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.92,
    },
    {
      company_id: companyMap['microsoft'],
      role: 'Software Engineer',
      level: Level.L5,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 8,
      base_salary: BigInt(4800000),
      bonus: BigInt(1000000),
      stock: BigInt(3000000),
      total_compensation: tc(4800000, 1000000, 3000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.94,
    },
    {
      company_id: companyMap['microsoft'],
      role: 'Data Scientist',
      level: Level.L4,
      location: 'Pune',
      currency: Currency.INR,
      experience_years: 3,
      base_salary: BigInt(2500000),
      bonus: BigInt(400000),
      stock: BigInt(800000),
      total_compensation: tc(2500000, 400000, 800000),
      source: Source.SCRAPED,
      confidence_score: 0.68,
    },
    {
      company_id: companyMap['microsoft'],
      role: 'Principal Engineer',
      level: Level.PRINCIPAL,
      location: 'Redmond',
      currency: Currency.USD,
      experience_years: 16,
      base_salary: BigInt(320000),
      bonus: BigInt(55000),
      stock: BigInt(220000),
      total_compensation: tc(320000, 55000, 220000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },

    // ── FLIPKART ──────────────────────────────────────────────────────────────
    {
      company_id: companyMap['flipkart'],
      role: 'Software Development Engineer',
      level: Level.SDE_I,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(1800000),
      bonus: BigInt(250000),
      stock: BigInt(500000),
      total_compensation: tc(1800000, 250000, 500000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },
    {
      company_id: companyMap['flipkart'],
      role: 'Software Development Engineer',
      level: Level.SDE_II,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 5,
      base_salary: BigInt(3000000),
      bonus: BigInt(500000),
      stock: BigInt(1200000),
      total_compensation: tc(3000000, 500000, 1200000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.91,
    },
    // Edge case: zero stock
    {
      company_id: companyMap['flipkart'],
      role: 'Product Manager',
      level: Level.L4,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 4,
      base_salary: BigInt(2800000),
      bonus: BigInt(400000),
      stock: BigInt(0),
      total_compensation: tc(2800000, 400000, 0),
      source: Source.SCRAPED,
      confidence_score: 0.66,
    },

    // ── MEESHO ────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['meesho'],
      role: 'Software Development Engineer',
      level: Level.SDE_I,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 1,
      base_salary: BigInt(1600000),
      bonus: BigInt(200000),
      stock: BigInt(400000),
      total_compensation: tc(1600000, 200000, 400000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.87,
    },
    {
      company_id: companyMap['meesho'],
      role: 'Software Development Engineer',
      level: Level.SDE_II,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 4,
      base_salary: BigInt(2600000),
      bonus: BigInt(400000),
      stock: BigInt(800000),
      total_compensation: tc(2600000, 400000, 800000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.88,
    },
    {
      company_id: companyMap['meesho'],
      role: 'Data Analyst',
      level: Level.L3,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(1200000),
      bonus: BigInt(150000),
      stock: BigInt(200000),
      total_compensation: tc(1200000, 150000, 200000),
      source: Source.SCRAPED,
      confidence_score: 0.6,
    },

    // ── NVIDIA ────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['nvidia'],
      role: 'Machine Learning Engineer',
      level: Level.L4,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 4,
      base_salary: BigInt(4000000),
      bonus: BigInt(800000),
      stock: BigInt(3000000),
      total_compensation: tc(4000000, 800000, 3000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },
    {
      company_id: companyMap['nvidia'],
      role: 'Machine Learning Engineer',
      level: Level.L5,
      location: 'Santa Clara',
      currency: Currency.USD,
      experience_years: 8,
      base_salary: BigInt(280000),
      bonus: BigInt(50000),
      stock: BigInt(200000),
      total_compensation: tc(280000, 50000, 200000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.91,
    },
    {
      company_id: companyMap['nvidia'],
      role: 'Software Engineer',
      level: Level.L4,
      location: 'Santa Clara',
      currency: Currency.USD,
      experience_years: 5,
      base_salary: BigInt(250000),
      bonus: BigInt(40000),
      stock: BigInt(150000),
      total_compensation: tc(250000, 40000, 150000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.89,
    },

    // ── TCS ───────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['tcs'],
      role: 'Software Engineer',
      level: Level.L3,
      location: 'Mumbai',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(700000),
      bonus: BigInt(50000),
      stock: BigInt(0),
      total_compensation: tc(700000, 50000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.88,
    },
    {
      company_id: companyMap['tcs'],
      role: 'Software Engineer',
      level: Level.L4,
      location: 'Pune',
      currency: Currency.INR,
      experience_years: 5,
      base_salary: BigInt(1000000),
      bonus: BigInt(80000),
      stock: BigInt(0),
      total_compensation: tc(1000000, 80000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },
    {
      company_id: companyMap['tcs'],
      role: 'Business Analyst',
      level: Level.L4,
      location: 'Hyderabad',
      currency: Currency.INR,
      experience_years: 4,
      base_salary: BigInt(900000),
      bonus: BigInt(70000),
      stock: BigInt(0),
      total_compensation: tc(900000, 70000, 0),
      source: Source.SCRAPED,
      confidence_score: 0.62,
    },
    {
      company_id: companyMap['tcs'],
      role: 'Project Manager',
      level: Level.L5,
      location: 'Delhi',
      currency: Currency.INR,
      experience_years: 10,
      base_salary: BigInt(1800000),
      bonus: BigInt(200000),
      stock: BigInt(0),
      total_compensation: tc(1800000, 200000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.85,
    },

    // ── INFOSYS ───────────────────────────────────────────────────────────────
    {
      company_id: companyMap['infosys'],
      role: 'Software Engineer',
      level: Level.L3,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(650000),
      bonus: BigInt(40000),
      stock: BigInt(0),
      total_compensation: tc(650000, 40000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.87,
    },
    {
      company_id: companyMap['infosys'],
      role: 'Software Engineer',
      level: Level.L4,
      location: 'Pune',
      currency: Currency.INR,
      experience_years: 5,
      base_salary: BigInt(950000),
      bonus: BigInt(70000),
      stock: BigInt(0),
      total_compensation: tc(950000, 70000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.89,
    },
    {
      company_id: companyMap['infosys'],
      role: 'Data Analyst',
      level: Level.L3,
      location: 'Hyderabad',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(700000),
      bonus: BigInt(50000),
      stock: BigInt(0),
      total_compensation: tc(700000, 50000, 0),
      source: Source.SCRAPED,
      confidence_score: 0.58,
    },

    // ── WIPRO ─────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['wipro'],
      role: 'Software Engineer',
      level: Level.L3,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(600000),
      bonus: BigInt(35000),
      stock: BigInt(0),
      total_compensation: tc(600000, 35000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.86,
    },
    {
      company_id: companyMap['wipro'],
      role: 'Software Engineer',
      level: Level.L4,
      location: 'Chennai',
      currency: Currency.INR,
      experience_years: 5,
      base_salary: BigInt(900000),
      bonus: BigInt(60000),
      stock: BigInt(0),
      total_compensation: tc(900000, 60000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.88,
    },

    // ── RAZORPAY ──────────────────────────────────────────────────────────────
    {
      company_id: companyMap['razorpay'],
      role: 'Software Development Engineer',
      level: Level.SDE_I,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 1,
      base_salary: BigInt(1700000),
      bonus: BigInt(220000),
      stock: BigInt(600000),
      total_compensation: tc(1700000, 220000, 600000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },
    {
      company_id: companyMap['razorpay'],
      role: 'Software Development Engineer',
      level: Level.SDE_II,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 4,
      base_salary: BigInt(2900000),
      bonus: BigInt(450000),
      stock: BigInt(1200000),
      total_compensation: tc(2900000, 450000, 1200000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.92,
    },
    {
      company_id: companyMap['razorpay'],
      role: 'Product Manager',
      level: Level.L4,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 5,
      base_salary: BigInt(2700000),
      bonus: BigInt(400000),
      stock: BigInt(1000000),
      total_compensation: tc(2700000, 400000, 1000000),
      source: Source.SCRAPED,
      confidence_score: 0.7,
    },

    // ── ZEPTO ─────────────────────────────────────────────────────────────────
    {
      company_id: companyMap['zepto'],
      role: 'Software Development Engineer',
      level: Level.SDE_I,
      location: 'Mumbai',
      currency: Currency.INR,
      experience_years: 1,
      base_salary: BigInt(1500000),
      bonus: BigInt(180000),
      stock: BigInt(500000),
      total_compensation: tc(1500000, 180000, 500000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.88,
    },
    {
      company_id: companyMap['zepto'],
      role: 'Software Development Engineer',
      level: Level.SDE_II,
      location: 'Mumbai',
      currency: Currency.INR,
      experience_years: 3,
      base_salary: BigInt(2400000),
      bonus: BigInt(350000),
      stock: BigInt(900000),
      total_compensation: tc(2400000, 350000, 900000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.89,
    },
    {
      company_id: companyMap['zepto'],
      role: 'Data Scientist',
      level: Level.L4,
      location: 'Mumbai',
      currency: Currency.INR,
      experience_years: 3,
      base_salary: BigInt(2200000),
      bonus: BigInt(300000),
      stock: BigInt(700000),
      total_compensation: tc(2200000, 300000, 700000),
      source: Source.SCRAPED,
      confidence_score: 0.65,
    },

    // ── ADDITIONAL RECORDS FOR DIVERSITY ──────────────────────────────────────
    {
      company_id: companyMap['google'],
      role: 'Data Scientist',
      level: Level.L4,
      location: 'Hyderabad',
      currency: Currency.INR,
      experience_years: 3,
      base_salary: BigInt(2800000),
      bonus: BigInt(500000),
      stock: BigInt(1200000),
      total_compensation: tc(2800000, 500000, 1200000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.91,
    },
    {
      company_id: companyMap['amazon'],
      role: 'Software Development Engineer',
      level: Level.SDE_I,
      location: 'Pune',
      currency: Currency.INR,
      experience_years: 2,
      base_salary: BigInt(2000000),
      bonus: BigInt(300000),
      stock: BigInt(600000),
      total_compensation: tc(2000000, 300000, 600000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.9,
    },
    {
      company_id: companyMap['microsoft'],
      role: 'Machine Learning Engineer',
      level: Level.L5,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 7,
      base_salary: BigInt(5200000),
      bonus: BigInt(1100000),
      stock: BigInt(4000000),
      total_compensation: tc(5200000, 1100000, 4000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.93,
    },
    {
      company_id: companyMap['flipkart'],
      role: 'Software Development Engineer',
      level: Level.SDE_III,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 8,
      base_salary: BigInt(4500000),
      bonus: BigInt(900000),
      stock: BigInt(3000000),
      total_compensation: tc(4500000, 900000, 3000000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.92,
    },
    {
      company_id: companyMap['nvidia'],
      role: 'Deep Learning Engineer',
      level: Level.L6,
      location: 'Santa Clara',
      currency: Currency.USD,
      experience_years: 12,
      base_salary: BigInt(350000),
      bonus: BigInt(70000),
      stock: BigInt(300000),
      total_compensation: tc(350000, 70000, 300000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.86,
    },
    {
      company_id: companyMap['razorpay'],
      role: 'Backend Engineer',
      level: Level.SDE_III,
      location: 'Bengaluru',
      currency: Currency.INR,
      experience_years: 7,
      base_salary: BigInt(4000000),
      bonus: BigInt(700000),
      stock: BigInt(2500000),
      total_compensation: tc(4000000, 700000, 2500000),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.91,
    },
    // Edge: very long company name record (to test layout stability)
    {
      company_id: companyMap['tcs'],
      role: 'Senior Solutions Architect & Technical Lead',
      level: Level.L5,
      location: 'Mumbai',
      currency: Currency.INR,
      experience_years: 12,
      base_salary: BigInt(2000000),
      bonus: BigInt(300000),
      stock: BigInt(0),
      total_compensation: tc(2000000, 300000, 0),
      source: Source.CONTRIBUTOR,
      confidence_score: 0.83,
    },
    // Edge: very large salary number (₹4,00,00,000)
    {
      company_id: companyMap['google'],
      role: 'VP Engineering',
      level: Level.L6,
      location: 'San Francisco',
      currency: Currency.INR,
      experience_years: 22,
      base_salary: BigInt(40000000),
      bonus: BigInt(8000000),
      stock: BigInt(15000000),
      total_compensation: tc(40000000, 8000000, 15000000),
      source: Source.AI_INFERRED,
      confidence_score: 0.55,
    },
  ]

  await prisma.salary.createMany({
    data: salaryData as any,
    skipDuplicates: true,
  })

  console.log(`✅ Created ${salaryData.length} salary records`)
  console.log('🎉 Seeding complete!')
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
